#!/usr/bin/env bash
# Continuous FedEvoSAC benchmark suite.
set -euo pipefail

cd "$(dirname "$0")"
export PYTHONPATH="$PWD:${PYTHONPATH:-}"

ENVS=${ENVS:-"Walker2d-v5 Hopper-v5"}
SEEDS=${SEEDS:-"0 1"}
FED_VARIANTS=${FED_VARIANTS:-"full"}
SAC_BASELINES=${SAC_BASELINES-"fedavg_sac fedbest_sac fedsoftmax_sac_noea fedmedian_sac"}
LOG_DIR=${LOG_DIR:-"logs/logs_fedevosac_continuous_mixed"}
SAC_LOG_DIR=${SAC_LOG_DIR:-"logs/logs_sac_continuous_mixed"}
COMPARISON_OUT_DIR=${COMPARISON_OUT_DIR:-"plots/fedevosac_continuous_comparison_round"}
CANDIDATE_OUT_DIR=${CANDIDATE_OUT_DIR:-"plots/fedevosac_continuous_candidate_round"}
ABLATION_OUT_DIR=${ABLATION_OUT_DIR:-"plots/fedevosac_continuous_ablations_round"}
SUMMARY_OUT_DIR=${SUMMARY_OUT_DIR:-"plots/fedevosac_continuous_tables"}
PLOT_X_AXIS=${PLOT_X_AXIS:-"round"}
PLOT_METRIC=${PLOT_METRIC:-"current"}
PLOT_VARIANCE=${PLOT_VARIANCE:-"none"}
PLOT_SMOOTH_WINDOW=${PLOT_SMOOTH_WINDOW:-"7"}
CLIENT_HETEROGENEITY=${CLIENT_HETEROGENEITY:-"0.0"}
CLIENT_HETEROGENEITY_MODE=${CLIENT_HETEROGENEITY_MODE:-"none"}
BUDGET_PRESET=${BUDGET_PRESET:-"reduced"}
TARGET_ENV_STEPS=${TARGET_ENV_STEPS:-""}
REPEAT_ID=${REPEAT_ID:-""}
SKIP_EXISTING=${SKIP_EXISTING:-"1"}
SKIP_PLOTS=${SKIP_PLOTS:-"0"}
BASELINE_UPDATE_TO_DATA_RATIO=${BASELINE_UPDATE_TO_DATA_RATIO:-"0.05"}
BASELINE_MAX_UPDATES_PER_ROUND=${BASELINE_MAX_UPDATES_PER_ROUND:-"20"}
BASELINE_BASE_UPDATES=${BASELINE_BASE_UPDATES:-"4"}
BASELINE_AGGREGATION_INTERVAL=${BASELINE_AGGREGATION_INTERVAL:-"5"}
BASELINE_SERVER_LEARNING_RATE=${BASELINE_SERVER_LEARNING_RATE:-"0.25"}
BASELINE_ACTOR_LR=${BASELINE_ACTOR_LR:-"0.0"}
BASELINE_POST_SYNC_CRITIC_WARMUP=${BASELINE_POST_SYNC_CRITIC_WARMUP:-"2"}
FED_INJECT_MARGIN=${FED_INJECT_MARGIN:-"-0.05"}
FED_EA_MUTATION_PROB=${FED_EA_MUTATION_PROB:-"0.90"}
FED_EA_RESET_PROB=${FED_EA_RESET_PROB:-"0.05"}
FED_DELTA_CLIP_NORM=${FED_DELTA_CLIP_NORM:-"5"}
FED_AGGREGATION_TEMPERATURE=${FED_AGGREGATION_TEMPERATURE:-"75"}
FED_RAW_SOFTMAX_TEMPERATURE=${FED_RAW_SOFTMAX_TEMPERATURE:-"75"}
FED_SCORE_NORMALIZATION=${FED_SCORE_NORMALIZATION:-"relative_gain"}
FED_SCORE_EMA_BETA=${FED_SCORE_EMA_BETA:-"0.90"}
FED_SCORE_MIN_STD=${FED_SCORE_MIN_STD:-"1.0"}
FED_SCORE_SCALE=${FED_SCORE_SCALE:-"1.0"}
FED_SCORE_WARMUP_ROUNDS=${FED_SCORE_WARMUP_ROUNDS:-"0"}
FED_SCORE_WARMUP_NORMALIZATION=${FED_SCORE_WARMUP_NORMALIZATION:-"batch_zscore"}
FED_INJECTION_WARMUP_ROUNDS=${FED_INJECTION_WARMUP_ROUNDS:-"0"}
FED_ARCHIVE_STD_PENALTY=${FED_ARCHIVE_STD_PENALTY:-"0.0"}
FED_INJECT_STD_PENALTY=${FED_INJECT_STD_PENALTY:-"0.0"}
FED_STAGNATION_PATIENCE=${FED_STAGNATION_PATIENCE:-"8"}
FED_STAGNATION_MIN_DELTA=${FED_STAGNATION_MIN_DELTA:-"5.0"}
FED_IMMIGRANT_FRACTION=${FED_IMMIGRANT_FRACTION:-"0.20"}
FED_CLIENT_ACTOR_LR=${FED_CLIENT_ACTOR_LR:-"0.0"}
FED_EA_INIT_MODE=${FED_EA_INIT_MODE:-"gaussian"}
FED_EA_INIT_SEED=${FED_EA_INIT_SEED:--1}
FED_EA_INIT_NOISE_SCALE=${FED_EA_INIT_NOISE_SCALE:-"0.05"}
FED_EA_MUTATION_SCALE_MODE=${FED_EA_MUTATION_SCALE_MODE:-"element"}
FED_EA_MUTATION_SCALE_FLOOR=${FED_EA_MUTATION_SCALE_FLOOR:-"0.001"}
FED_EA_MUTATE_BIAS=${FED_EA_MUTATE_BIAS:-"0"}
FED_EA_FREEZE_SAC_LOG_STD=${FED_EA_FREEZE_SAC_LOG_STD:-"0"}
FED_CLIENT_VALIDATION_EPISODES=${FED_CLIENT_VALIDATION_EPISODES:-"0"}
FED_CLIENT_ROLLBACK_MARGIN=${FED_CLIENT_ROLLBACK_MARGIN:-"0.0"}
FED_STAGNATION_MAX_BOOSTS=${FED_STAGNATION_MAX_BOOSTS:-"-1"}
FED_STAGNATION_BOOST_COOLDOWN=${FED_STAGNATION_BOOST_COOLDOWN:-"0"}
FED_INJECT_NOISE=${FED_INJECT_NOISE:-"0.05"}
FED_MIGRATION_BLEND=${FED_MIGRATION_BLEND:-"0.35"}

run_is_complete() {
  local metrics_path=$1
  local target_steps=$2
  [[ -s "$metrics_path" ]] || return 1
  awk -F, -v target="$target_steps" '
    NR == 1 {
      for (i = 1; i <= NF; i++) if ($i == "total_env_steps") step_col = i
      next
    }
    step_col && $step_col != "" { last = $step_col + 0 }
    END { exit !(last >= target) }
  ' "$metrics_path"
}

for ENV_NAME in $ENVS; do
  read POP CLIENTS GENS STEPS <<<"$(python3 - <<PY
from src.config import env_run_preset
p = env_run_preset('$ENV_NAME')
print(p['population_size'], p['num_workers'], p['max_generations'], p['max_episode_steps'])
PY
)"
  if [[ "$BUDGET_PRESET" == "reduced" ]]; then
    POP=${FED_POPULATION_SIZE:-8}
    GENS=${FED_MAX_GENERATIONS:-$(( GENS < 15 ? GENS : 15 ))}
    EVAL_EPISODES=${FED_EVAL_EPISODES:-2}
    ARCHIVE_EVAL_CANDIDATES=${FED_ARCHIVE_EVAL_CANDIDATES:-2}
    ARCHIVE_EVAL_EPISODES=${FED_ARCHIVE_EVAL_EPISODES:-2}
  else
    POP=${FED_POPULATION_SIZE:-$POP}
    GENS=${FED_MAX_GENERATIONS:-$GENS}
    EVAL_EPISODES=${FED_EVAL_EPISODES:-3}
    CLIENT_ROLLOUTS=${FED_CLIENT_ROLLOUTS:-2}
    CLIENT_UPDATES=${FED_CLIENT_UPDATES:-8}
    ARCHIVE_EVAL_CANDIDATES=${FED_ARCHIVE_EVAL_CANDIDATES:-3}
    ARCHIVE_EVAL_EPISODES=${FED_ARCHIVE_EVAL_EPISODES:-3}
  fi
  SCORE_WARMUP_ROUNDS="$FED_SCORE_WARMUP_ROUNDS"
  SCORE_WARMUP_NORMALIZATION="$FED_SCORE_WARMUP_NORMALIZATION"
  SCORE_NORMALIZATION="$FED_SCORE_NORMALIZATION"
  SCORE_SCALE="$FED_SCORE_SCALE"
  INJECTION_WARMUP_ROUNDS="$FED_INJECTION_WARMUP_ROUNDS"
  EA_MUTATION_PROB="$FED_EA_MUTATION_PROB"
  EA_RESET_PROB="$FED_EA_RESET_PROB"
  INJECT_MARGIN="$FED_INJECT_MARGIN"
  DELTA_CLIP_NORM="$FED_DELTA_CLIP_NORM"
  AGGREGATION_TEMPERATURE="$FED_AGGREGATION_TEMPERATURE"
  RAW_SOFTMAX_TEMPERATURE="$FED_RAW_SOFTMAX_TEMPERATURE"
  ENV_CLIENT_HETEROGENEITY="$CLIENT_HETEROGENEITY"
  ENV_CLIENT_HETEROGENEITY_MODE="$CLIENT_HETEROGENEITY_MODE"
  ARCHIVE_STD_PENALTY="$FED_ARCHIVE_STD_PENALTY"
  INJECT_STD_PENALTY="$FED_INJECT_STD_PENALTY"
  STAGNATION_PATIENCE="$FED_STAGNATION_PATIENCE"
  STAGNATION_MIN_DELTA="$FED_STAGNATION_MIN_DELTA"
  IMMIGRANT_FRACTION="$FED_IMMIGRANT_FRACTION"
  CLIENT_ACTOR_LR="$FED_CLIENT_ACTOR_LR"
  EA_INIT_MODE="$FED_EA_INIT_MODE"
  EA_INIT_SEED="$FED_EA_INIT_SEED"
  EA_INIT_NOISE_SCALE="$FED_EA_INIT_NOISE_SCALE"
  EA_MUTATION_SCALE_MODE="$FED_EA_MUTATION_SCALE_MODE"
  EA_MUTATION_SCALE_FLOOR="$FED_EA_MUTATION_SCALE_FLOOR"
  EA_MUTATE_BIAS="$FED_EA_MUTATE_BIAS"
  EA_FREEZE_SAC_LOG_STD="$FED_EA_FREEZE_SAC_LOG_STD"
  CLIENT_VALIDATION_EPISODES="$FED_CLIENT_VALIDATION_EPISODES"
  CLIENT_ROLLBACK_MARGIN="$FED_CLIENT_ROLLBACK_MARGIN"
  STAGNATION_MAX_BOOSTS="$FED_STAGNATION_MAX_BOOSTS"
  STAGNATION_BOOST_COOLDOWN="$FED_STAGNATION_BOOST_COOLDOWN"
  INJECT_NOISE="$FED_INJECT_NOISE"
  MIGRATION_BLEND="$FED_MIGRATION_BLEND"
  WALKER_HEALTHY_REWARD=1.0
  WALKER_FORWARD_REWARD_WEIGHT=1.0
  THIS_BASELINE_UPDATE_TO_DATA_RATIO="$BASELINE_UPDATE_TO_DATA_RATIO"
  THIS_BASELINE_MAX_UPDATES_PER_ROUND="$BASELINE_MAX_UPDATES_PER_ROUND"
  THIS_BASELINE_BASE_UPDATES="$BASELINE_BASE_UPDATES"
  THIS_BASELINE_ACTOR_LR="$BASELINE_ACTOR_LR"
  THIS_BASELINE_POST_SYNC_CRITIC_WARMUP="$BASELINE_POST_SYNC_CRITIC_WARMUP"
  case "$ENV_NAME" in
    Ant-v5)
      POP=${FED_ANT_POPULATION_SIZE:-${FED_POPULATION_SIZE:-12}}
      STEPS=${FED_ANT_MAX_EPISODE_STEPS:-${FED_MAX_EPISODE_STEPS:-1000}}
      FED_AGG_INTERVAL=${FED_ANT_AGGREGATION_INTERVAL:-4}
      CLIENT_ROLLOUTS=${FED_ANT_CLIENT_ROLLOUTS:-1}
      CLIENT_UPDATES=${FED_ANT_CLIENT_UPDATES:-8}
      CLIENT_CRITIC_WARMUP=${FED_ANT_CLIENT_CRITIC_WARMUP:-4}
      ARCHIVE_EVAL_CANDIDATES=${FED_ANT_ARCHIVE_EVAL_CANDIDATES:-2}
      ARCHIVE_EVAL_EPISODES=${FED_ANT_ARCHIVE_EVAL_EPISODES:-1}
      EA_MUTATION_PROB=${FED_ANT_EA_MUTATION_PROB:-0.84}
      EA_RESET_PROB=${FED_ANT_EA_RESET_PROB:-0.03}
      INJECT_MARGIN=${FED_ANT_INJECT_MARGIN:-"-0.03"}
      DELTA_CLIP_NORM=${FED_ANT_DELTA_CLIP_NORM:-4}
      AGGREGATION_TEMPERATURE=${FED_ANT_AGGREGATION_TEMPERATURE:-60}
      SCORE_SCALE=${FED_ANT_SCORE_SCALE:-4.0}
      SCORE_WARMUP_ROUNDS=${FED_ANT_SCORE_WARMUP_ROUNDS:-2}
      SCORE_WARMUP_NORMALIZATION=${FED_ANT_SCORE_WARMUP_NORMALIZATION:-batch_zscore}
      INJECTION_WARMUP_ROUNDS=${FED_ANT_INJECTION_WARMUP_ROUNDS:-2}
      STAGNATION_PATIENCE=${FED_ANT_STAGNATION_PATIENCE:-6}
      ENV_CLIENT_HETEROGENEITY=${FED_ANT_CLIENT_HETEROGENEITY:-0.15}
      ENV_CLIENT_HETEROGENEITY_MODE=${FED_ANT_CLIENT_HETEROGENEITY_MODE:-env_params_only}
      ;;
    Pusher-v5)
      POP=${FED_PUSHER_POPULATION_SIZE:-${FED_POPULATION_SIZE:-12}}
      STEPS=${FED_PUSHER_MAX_EPISODE_STEPS:-${FED_MAX_EPISODE_STEPS:-100}}
      FED_AGG_INTERVAL=${FED_PUSHER_AGGREGATION_INTERVAL:-4}
      CLIENT_ROLLOUTS=${FED_PUSHER_CLIENT_ROLLOUTS:-2}
      CLIENT_UPDATES=${FED_PUSHER_CLIENT_UPDATES:-16}
      CLIENT_CRITIC_WARMUP=${FED_PUSHER_CLIENT_CRITIC_WARMUP:-8}
      ARCHIVE_EVAL_CANDIDATES=${FED_PUSHER_ARCHIVE_EVAL_CANDIDATES:-2}
      ARCHIVE_EVAL_EPISODES=${FED_PUSHER_ARCHIVE_EVAL_EPISODES:-2}
      EA_MUTATION_PROB=${FED_PUSHER_EA_MUTATION_PROB:-0.86}
      EA_RESET_PROB=${FED_PUSHER_EA_RESET_PROB:-0.03}
      INJECT_MARGIN=${FED_PUSHER_INJECT_MARGIN:-"-0.03"}
      DELTA_CLIP_NORM=${FED_PUSHER_DELTA_CLIP_NORM:-4}
      AGGREGATION_TEMPERATURE=${FED_PUSHER_AGGREGATION_TEMPERATURE:-60}
      SCORE_SCALE=${FED_PUSHER_SCORE_SCALE:-4.0}
      SCORE_WARMUP_ROUNDS=${FED_PUSHER_SCORE_WARMUP_ROUNDS:-2}
      SCORE_WARMUP_NORMALIZATION=${FED_PUSHER_SCORE_WARMUP_NORMALIZATION:-batch_zscore}
      INJECTION_WARMUP_ROUNDS=${FED_PUSHER_INJECTION_WARMUP_ROUNDS:-2}
      STAGNATION_PATIENCE=${FED_PUSHER_STAGNATION_PATIENCE:-6}
      STAGNATION_MIN_DELTA=${FED_PUSHER_STAGNATION_MIN_DELTA:-1.0}
      ENV_CLIENT_HETEROGENEITY=${FED_PUSHER_CLIENT_HETEROGENEITY:-0.0}
      ENV_CLIENT_HETEROGENEITY_MODE=${FED_PUSHER_CLIENT_HETEROGENEITY_MODE:-none}
      ;;
    Reacher-v5)
      STEPS=${FED_MAX_EPISODE_STEPS:-50}
      FED_AGG_INTERVAL=${FED_AGGREGATION_INTERVAL:-1}
      CLIENT_ROLLOUTS=${FED_CLIENT_ROLLOUTS:-4}
      CLIENT_UPDATES=${FED_CLIENT_UPDATES:-12}
      CLIENT_CRITIC_WARMUP=${FED_CLIENT_CRITIC_WARMUP:-6}
      ;;
    Swimmer-v5)
      POP=${FED_SWIMMER_POPULATION_SIZE:-11}
      STEPS=${FED_MAX_EPISODE_STEPS:-1000}
      FED_AGG_INTERVAL=${FED_AGGREGATION_INTERVAL:-2}
      CLIENT_ROLLOUTS=${FED_SWIMMER_CLIENT_ROLLOUTS:-2}
      CLIENT_UPDATES=${FED_SWIMMER_CLIENT_UPDATES:-128}
      CLIENT_CRITIC_WARMUP=${FED_SWIMMER_CLIENT_CRITIC_WARMUP:-64}
      CLIENT_ACTOR_LR=${FED_SWIMMER_CLIENT_ACTOR_LR:-0.0001}
      EA_MUTATION_PROB=${FED_SWIMMER_EA_MUTATION_PROB:-0.78}
      EA_RESET_PROB=${FED_SWIMMER_EA_RESET_PROB:-0.01}
      EA_INIT_MODE=${FED_SWIMMER_EA_INIT_MODE:-anchor_antithetic}
      # Keep the default per-run seed independent. A shared init seed remains
      # available for controlled diagnostics, not for formal seed statistics.
      EA_INIT_SEED=${FED_SWIMMER_EA_INIT_SEED:--1}
      EA_INIT_NOISE_SCALE=${FED_SWIMMER_EA_INIT_NOISE_SCALE:-0.12}
      EA_MUTATION_SCALE_MODE=${FED_SWIMMER_EA_MUTATION_SCALE_MODE:-layer_rms}
      EA_MUTATION_SCALE_FLOOR=${FED_SWIMMER_EA_MUTATION_SCALE_FLOOR:-0.05}
      EA_MUTATE_BIAS=${FED_SWIMMER_EA_MUTATE_BIAS:-1}
      EA_FREEZE_SAC_LOG_STD=${FED_SWIMMER_EA_FREEZE_SAC_LOG_STD:-1}
      CLIENT_VALIDATION_EPISODES=${FED_SWIMMER_CLIENT_VALIDATION_EPISODES:-1}
      CLIENT_ROLLBACK_MARGIN=${FED_SWIMMER_CLIENT_ROLLBACK_MARGIN:-0.0}
      INJECT_MARGIN=${FED_SWIMMER_INJECT_MARGIN:-"-0.02"}
      INJECT_NOISE=${FED_SWIMMER_INJECT_NOISE:-0.005}
      MIGRATION_BLEND=${FED_SWIMMER_MIGRATION_BLEND:-0.50}
      DELTA_CLIP_NORM=${FED_SWIMMER_DELTA_CLIP_NORM:-3}
      AGGREGATION_TEMPERATURE=${FED_SWIMMER_AGGREGATION_TEMPERATURE:-4.0}
      RAW_SOFTMAX_TEMPERATURE=${FED_SWIMMER_RAW_SOFTMAX_TEMPERATURE:-15.0}
      # Keep validation independent, but do not spend nearly half of the
      # interaction budget re-evaluating the archive on this long-horizon task.
      ARCHIVE_EVAL_CANDIDATES=${FED_SWIMMER_ARCHIVE_EVAL_CANDIDATES:-2}
      ARCHIVE_EVAL_EPISODES=${FED_SWIMMER_ARCHIVE_EVAL_EPISODES:-2}
      SCORE_WARMUP_ROUNDS=${FED_SWIMMER_SCORE_WARMUP_ROUNDS:-2}
      SCORE_WARMUP_NORMALIZATION=${FED_SWIMMER_SCORE_WARMUP_NORMALIZATION:-batch_zscore}
      SCORE_SCALE=${FED_SWIMMER_SCORE_SCALE:-4.0}
      INJECTION_WARMUP_ROUNDS=${FED_SWIMMER_INJECTION_WARMUP_ROUNDS:-2}
      ARCHIVE_STD_PENALTY=${FED_SWIMMER_ARCHIVE_STD_PENALTY:-0.50}
      INJECT_STD_PENALTY=${FED_SWIMMER_INJECT_STD_PENALTY:-0.50}
      STAGNATION_PATIENCE=${FED_SWIMMER_STAGNATION_PATIENCE:-6}
      STAGNATION_MIN_DELTA=${FED_SWIMMER_STAGNATION_MIN_DELTA:-2.0}
      STAGNATION_MAX_BOOSTS=${FED_SWIMMER_STAGNATION_MAX_BOOSTS:-2}
      STAGNATION_BOOST_COOLDOWN=${FED_SWIMMER_STAGNATION_BOOST_COOLDOWN:-12}
      IMMIGRANT_FRACTION=${FED_SWIMMER_IMMIGRANT_FRACTION:-0.12}
      ENV_CLIENT_HETEROGENEITY=${FED_SWIMMER_CLIENT_HETEROGENEITY:-0.12}
      ENV_CLIENT_HETEROGENEITY_MODE=${FED_SWIMMER_CLIENT_HETEROGENEITY_MODE:-env_params_only}
      ;;
    Hopper-v5)
      POP=${FED_HOPPER_POPULATION_SIZE:-13}
      STEPS=${FED_MAX_EPISODE_STEPS:-1000}
      FED_AGG_INTERVAL=${FED_AGGREGATION_INTERVAL:-4}
      CLIENT_ROLLOUTS=${FED_HOPPER_CLIENT_ROLLOUTS:-2}
      CLIENT_UPDATES=${FED_HOPPER_CLIENT_UPDATES:-64}
      CLIENT_CRITIC_WARMUP=${FED_HOPPER_CLIENT_CRITIC_WARMUP:-32}
      CLIENT_ACTOR_LR=${FED_HOPPER_CLIENT_ACTOR_LR:-0.0001}
      CLIENT_VALIDATION_EPISODES=${FED_HOPPER_CLIENT_VALIDATION_EPISODES:-1}
      CLIENT_ROLLBACK_MARGIN=${FED_HOPPER_CLIENT_ROLLBACK_MARGIN:-0.0}
      ARCHIVE_EVAL_CANDIDATES=${FED_HOPPER_ARCHIVE_EVAL_CANDIDATES:-3}
      ARCHIVE_EVAL_EPISODES=${FED_HOPPER_ARCHIVE_EVAL_EPISODES:-2}
      EA_MUTATION_PROB=${FED_HOPPER_EA_MUTATION_PROB:-0.82}
      EA_RESET_PROB=${FED_HOPPER_EA_RESET_PROB:-0.02}
      EA_INIT_MODE=${FED_HOPPER_EA_INIT_MODE:-anchor_antithetic}
      EA_INIT_SEED=${FED_HOPPER_EA_INIT_SEED:--1}
      EA_INIT_NOISE_SCALE=${FED_HOPPER_EA_INIT_NOISE_SCALE:-0.12}
      EA_MUTATION_SCALE_MODE=${FED_HOPPER_EA_MUTATION_SCALE_MODE:-layer_rms}
      EA_MUTATION_SCALE_FLOOR=${FED_HOPPER_EA_MUTATION_SCALE_FLOOR:-0.05}
      EA_MUTATE_BIAS=${FED_HOPPER_EA_MUTATE_BIAS:-1}
      EA_FREEZE_SAC_LOG_STD=${FED_HOPPER_EA_FREEZE_SAC_LOG_STD:-1}
      INJECT_MARGIN=${FED_HOPPER_INJECT_MARGIN:-"-0.02"}
      INJECT_NOISE=${FED_HOPPER_INJECT_NOISE:-0.005}
      MIGRATION_BLEND=${FED_HOPPER_MIGRATION_BLEND:-0.50}
      DELTA_CLIP_NORM=${FED_HOPPER_DELTA_CLIP_NORM:-4}
      AGGREGATION_TEMPERATURE=${FED_HOPPER_AGGREGATION_TEMPERATURE:-1.0}
      RAW_SOFTMAX_TEMPERATURE=${FED_HOPPER_RAW_SOFTMAX_TEMPERATURE:-50.0}
      SCORE_SCALE=${FED_HOPPER_SCORE_SCALE:-1.0}
      SCORE_NORMALIZATION=${FED_HOPPER_SCORE_NORMALIZATION:-$SCORE_NORMALIZATION}
      SCORE_WARMUP_ROUNDS=${FED_HOPPER_SCORE_WARMUP_ROUNDS:-2}
      SCORE_WARMUP_NORMALIZATION=${FED_HOPPER_SCORE_WARMUP_NORMALIZATION:-batch_zscore}
      INJECTION_WARMUP_ROUNDS=${FED_HOPPER_INJECTION_WARMUP_ROUNDS:-2}
      ARCHIVE_STD_PENALTY=${FED_HOPPER_ARCHIVE_STD_PENALTY:-0.25}
      INJECT_STD_PENALTY=${FED_HOPPER_INJECT_STD_PENALTY:-0.25}
      STAGNATION_PATIENCE=${FED_HOPPER_STAGNATION_PATIENCE:-8}
      STAGNATION_MAX_BOOSTS=${FED_HOPPER_STAGNATION_MAX_BOOSTS:-2}
      STAGNATION_BOOST_COOLDOWN=${FED_HOPPER_STAGNATION_BOOST_COOLDOWN:-12}
      ENV_CLIENT_HETEROGENEITY=${FED_HOPPER_CLIENT_HETEROGENEITY:-0.25}
      ENV_CLIENT_HETEROGENEITY_MODE=${FED_HOPPER_CLIENT_HETEROGENEITY_MODE:-env_params_only}
      ;;
    Walker2d-v5)
      POP=${FED_WALKER2D_POPULATION_SIZE:-13}
      STEPS=${FED_MAX_EPISODE_STEPS:-1000}
      FED_AGG_INTERVAL=${FED_WALKER2D_AGGREGATION_INTERVAL:-5}
      CLIENT_ROLLOUTS=${FED_WALKER2D_CLIENT_ROLLOUTS:-2}
      CLIENT_UPDATES=${FED_WALKER2D_CLIENT_UPDATES:-256}
      CLIENT_CRITIC_WARMUP=${FED_WALKER2D_CLIENT_CRITIC_WARMUP:-192}
      CLIENT_ACTOR_LR=${FED_WALKER2D_CLIENT_ACTOR_LR:-0.00003}
      CLIENT_VALIDATION_EPISODES=${FED_WALKER2D_CLIENT_VALIDATION_EPISODES:-1}
      CLIENT_ROLLBACK_MARGIN=${FED_WALKER2D_CLIENT_ROLLBACK_MARGIN:-0.0}
      ARCHIVE_EVAL_CANDIDATES=${FED_WALKER2D_ARCHIVE_EVAL_CANDIDATES:-2}
      ARCHIVE_EVAL_EPISODES=${FED_WALKER2D_ARCHIVE_EVAL_EPISODES:-2}
      EA_MUTATION_PROB=${FED_WALKER2D_EA_MUTATION_PROB:-0.86}
      EA_RESET_PROB=${FED_WALKER2D_EA_RESET_PROB:-0.03}
      EA_INIT_MODE=${FED_WALKER2D_EA_INIT_MODE:-anchor_antithetic}
      EA_INIT_SEED=${FED_WALKER2D_EA_INIT_SEED:--1}
      EA_INIT_NOISE_SCALE=${FED_WALKER2D_EA_INIT_NOISE_SCALE:-0.12}
      EA_MUTATION_SCALE_MODE=${FED_WALKER2D_EA_MUTATION_SCALE_MODE:-layer_rms}
      EA_MUTATION_SCALE_FLOOR=${FED_WALKER2D_EA_MUTATION_SCALE_FLOOR:-0.05}
      EA_MUTATE_BIAS=${FED_WALKER2D_EA_MUTATE_BIAS:-1}
      EA_FREEZE_SAC_LOG_STD=${FED_WALKER2D_EA_FREEZE_SAC_LOG_STD:-1}
      INJECT_MARGIN=${FED_WALKER2D_INJECT_MARGIN:-"-0.02"}
      INJECT_NOISE=${FED_WALKER2D_INJECT_NOISE:-0.005}
      MIGRATION_BLEND=${FED_WALKER2D_MIGRATION_BLEND:-0.50}
      DELTA_CLIP_NORM=${FED_WALKER2D_DELTA_CLIP_NORM:-4}
      AGGREGATION_TEMPERATURE=${FED_WALKER2D_AGGREGATION_TEMPERATURE:-8.0}
      RAW_SOFTMAX_TEMPERATURE=${FED_WALKER2D_RAW_SOFTMAX_TEMPERATURE:-60.0}
      SCORE_SCALE=${FED_WALKER2D_SCORE_SCALE:-8.0}
      SCORE_NORMALIZATION=${FED_WALKER2D_SCORE_NORMALIZATION:-batch_zscore}
      SCORE_WARMUP_ROUNDS=${FED_WALKER2D_SCORE_WARMUP_ROUNDS:-2}
      SCORE_WARMUP_NORMALIZATION=${FED_WALKER2D_SCORE_WARMUP_NORMALIZATION:-batch_zscore}
      INJECTION_WARMUP_ROUNDS=${FED_WALKER2D_INJECTION_WARMUP_ROUNDS:-2}
      ARCHIVE_STD_PENALTY=${FED_WALKER2D_ARCHIVE_STD_PENALTY:-0.25}
      INJECT_STD_PENALTY=${FED_WALKER2D_INJECT_STD_PENALTY:-0.25}
      STAGNATION_PATIENCE=${FED_WALKER2D_STAGNATION_PATIENCE:-8}
      STAGNATION_MAX_BOOSTS=${FED_WALKER2D_STAGNATION_MAX_BOOSTS:-2}
      STAGNATION_BOOST_COOLDOWN=${FED_WALKER2D_STAGNATION_BOOST_COOLDOWN:-12}
      ENV_CLIENT_HETEROGENEITY=${FED_WALKER2D_CLIENT_HETEROGENEITY:-0.30}
      ENV_CLIENT_HETEROGENEITY_MODE=${FED_WALKER2D_CLIENT_HETEROGENEITY_MODE:-env_params_only}
      WALKER_HEALTHY_REWARD=${FED_WALKER2D_HEALTHY_REWARD:-0.05}
      WALKER_FORWARD_REWARD_WEIGHT=${FED_WALKER2D_FORWARD_REWARD_WEIGHT:-1.0}
      THIS_BASELINE_UPDATE_TO_DATA_RATIO=${BASELINE_WALKER2D_UPDATE_TO_DATA_RATIO:-0.25}
      THIS_BASELINE_MAX_UPDATES_PER_ROUND=${BASELINE_WALKER2D_MAX_UPDATES_PER_ROUND:-256}
      THIS_BASELINE_BASE_UPDATES=${BASELINE_WALKER2D_BASE_UPDATES:-64}
      THIS_BASELINE_ACTOR_LR=${BASELINE_WALKER2D_ACTOR_LR:-0.0001}
      THIS_BASELINE_POST_SYNC_CRITIC_WARMUP=${BASELINE_WALKER2D_POST_SYNC_CRITIC_WARMUP:-32}
      ;;
  esac
  CLIENTS=${FED_NUM_CLIENTS:-3}
  WORKERS=${FED_NUM_WORKERS:-$CLIENTS}
  if [[ -n "$TARGET_ENV_STEPS" ]]; then
    TARGET_STEPS=$TARGET_ENV_STEPS
  elif [[ "$BUDGET_PRESET" == "converged" ]]; then
    case "$ENV_NAME" in
      Swimmer-v5) TARGET_STEPS=${FED_SWIMMER_TARGET_ENV_STEPS:-1200000} ;;
      Pusher-v5) TARGET_STEPS=${FED_PUSHER_TARGET_ENV_STEPS:-300000} ;;
      Walker2d-v5) TARGET_STEPS=${FED_WALKER2D_TARGET_ENV_STEPS:-1200000} ;;
      Hopper-v5) TARGET_STEPS=${FED_HOPPER_TARGET_ENV_STEPS:-1200000} ;;
      *) TARGET_STEPS=1200000 ;;
    esac
  else
    TARGET_STEPS=459000
  fi
  if [[ -n "${BASELINE_ROUNDS:-}" ]]; then
    THIS_BASELINE_ROUNDS="$BASELINE_ROUNDS"
  else
    THIS_BASELINE_ROUNDS=$(python3 - <<PY
import math
print(max(1, math.ceil(int('$TARGET_STEPS') / max(1, int('$CLIENTS') * int('$STEPS')))))
PY
)
  fi
  echo "$ENV_NAME continuous budget=$BUDGET_PRESET target_env_steps=$TARGET_STEPS baseline_rounds>=$THIS_BASELINE_ROUNDS heterogeneity=$ENV_CLIENT_HETEROGENEITY/$ENV_CLIENT_HETEROGENEITY_MODE"

  SEED_SLOT=0
  for SEED in $SEEDS; do
    EXP_SUFFIX=""
    if [[ -n "$REPEAT_ID" ]]; then
      EXP_SUFFIX="_r${REPEAT_ID}"
    fi
    for VARIANT in $FED_VARIANTS; do
      EXP="fedevosac_${ENV_NAME}_${VARIANT}_s${SEED}${EXP_SUFFIX}"
      if [[ "$SKIP_EXISTING" == "1" ]] && run_is_complete "$LOG_DIR/$EXP/metrics.csv" "$TARGET_STEPS"; then
        echo "Skip complete run: $EXP"
        continue
      fi
      EXTRA_FED_ARGS=()
      if [[ "$EA_MUTATE_BIAS" == "1" ]]; then
        EXTRA_FED_ARGS+=(--ea-mutate-bias)
      fi
      if [[ "$EA_FREEZE_SAC_LOG_STD" == "1" ]]; then
        EXTRA_FED_ARGS+=(--ea-freeze-sac-log-std)
      fi
      python3 -m src.main \
        --env "$ENV_NAME" \
        --mode fed_evo_rl \
        --fed-ablation "$VARIANT" \
        --algorithm SAC \
        --population-size "$POP" \
        --num-workers "$WORKERS" \
        --num-clients "$CLIENTS" \
        --max-generations "$GENS" \
        --target-env-steps "$TARGET_STEPS" \
        --max-episode-steps "$STEPS" \
        --client-heterogeneity "$ENV_CLIENT_HETEROGENEITY" \
        --client-heterogeneity-mode "$ENV_CLIENT_HETEROGENEITY_MODE" \
        --walker-healthy-reward "$WALKER_HEALTHY_REWARD" \
        --walker-forward-reward-weight "$WALKER_FORWARD_REWARD_WEIGHT" \
        --fed-aggregation softmax \
        --fed-aggregation-interval "$FED_AGG_INTERVAL" \
        --fed-aggregation-temperature "$AGGREGATION_TEMPERATURE" \
        --fed-raw-softmax-temperature "$RAW_SOFTMAX_TEMPERATURE" \
        --fed-score-normalization "$SCORE_NORMALIZATION" \
        --fed-score-warmup-rounds "$SCORE_WARMUP_ROUNDS" \
        --fed-score-warmup-normalization "$SCORE_WARMUP_NORMALIZATION" \
        --fed-score-ema-beta "$FED_SCORE_EMA_BETA" \
        --fed-score-min-std "$FED_SCORE_MIN_STD" \
        --fed-score-scale "$SCORE_SCALE" \
        --fed-injection-warmup-rounds "$INJECTION_WARMUP_ROUNDS" \
        --fed-inject-margin "$INJECT_MARGIN" \
        --inject-noise "$INJECT_NOISE" \
        --migration-blend "$MIGRATION_BLEND" \
        --fed-delta-clip-norm "$DELTA_CLIP_NORM" \
        --ea-mutation-prob "$EA_MUTATION_PROB" \
        --ea-mutation-scale-mode "$EA_MUTATION_SCALE_MODE" \
        --ea-mutation-scale-floor "$EA_MUTATION_SCALE_FLOOR" \
        --ea-prob-reset-and-super "$EA_RESET_PROB" \
        --ea-init-mode "$EA_INIT_MODE" \
        --ea-init-seed "$EA_INIT_SEED" \
        --ea-init-noise-scale "$EA_INIT_NOISE_SCALE" \
        --ea-weight-clip 5 \
        --elite-archive-size 5 \
        --elite-archive-restore-copies 1 \
        --archive-eval-candidates "$ARCHIVE_EVAL_CANDIDATES" \
        --archive-eval-episodes "$ARCHIVE_EVAL_EPISODES" \
        --archive-std-penalty "$ARCHIVE_STD_PENALTY" \
        --fed-inject-std-penalty "$INJECT_STD_PENALTY" \
        --client-rollouts "$CLIENT_ROLLOUTS" \
        --client-updates "$CLIENT_UPDATES" \
        --client-critic-warmup-updates "$CLIENT_CRITIC_WARMUP" \
        --client-actor-lr "$CLIENT_ACTOR_LR" \
        --client-validation-episodes "$CLIENT_VALIDATION_EPISODES" \
        --client-rollback-margin "$CLIENT_ROLLBACK_MARGIN" \
        --batch-size 64 \
        --eval-episodes "$EVAL_EPISODES" \
        --seed "$SEED" \
        --repeat-id "$REPEAT_ID" \
        --seed-slot "$SEED_SLOT" \
        --stagnation-patience "$STAGNATION_PATIENCE" \
        --stagnation-min-delta "$STAGNATION_MIN_DELTA" \
        --stagnation-max-boosts "$STAGNATION_MAX_BOOSTS" \
        --stagnation-boost-cooldown "$STAGNATION_BOOST_COOLDOWN" \
        --immigrant-fraction "$IMMIGRANT_FRACTION" \
        --log-dir "$LOG_DIR" \
        --exp-name "$EXP" \
        "${EXTRA_FED_ARGS[@]}"
    done
    for MODE in $SAC_BASELINES; do
      EXP="${MODE}_${ENV_NAME}_s${SEED}${EXP_SUFFIX}"
      if [[ "$SKIP_EXISTING" == "1" ]] && run_is_complete "$SAC_LOG_DIR/$EXP/metrics.csv" "$TARGET_STEPS"; then
        echo "Skip complete run: $EXP"
        continue
      fi
      python3 scripts/train_continuous_sac_baseline.py \
        --env "$ENV_NAME" \
        --seed "$SEED" \
        --repeat-id "$REPEAT_ID" \
        --seed-slot "$SEED_SLOT" \
        --rounds "$THIS_BASELINE_ROUNDS" \
        --target-env-steps "$TARGET_STEPS" \
        --num-workers "$CLIENTS" \
        --updates "$THIS_BASELINE_BASE_UPDATES" \
        --update-to-data-ratio "$THIS_BASELINE_UPDATE_TO_DATA_RATIO" \
        --max-updates-per-round "$THIS_BASELINE_MAX_UPDATES_PER_ROUND" \
        --actor-lr "$THIS_BASELINE_ACTOR_LR" \
        --post-sync-critic-warmup-updates "$THIS_BASELINE_POST_SYNC_CRITIC_WARMUP" \
        --aggregation-interval "$BASELINE_AGGREGATION_INTERVAL" \
        --server-learning-rate "$BASELINE_SERVER_LEARNING_RATE" \
        --aggregation-eval-episodes "$ARCHIVE_EVAL_EPISODES" \
        --eval-interval "$BASELINE_AGGREGATION_INTERVAL" \
        --batch-size 64 \
        --eval-episodes "$EVAL_EPISODES" \
        --max-episode-steps "$STEPS" \
        --client-heterogeneity "$ENV_CLIENT_HETEROGENEITY" \
        --client-heterogeneity-mode "$ENV_CLIENT_HETEROGENEITY_MODE" \
        --walker-healthy-reward "$WALKER_HEALTHY_REWARD" \
        --walker-forward-reward-weight "$WALKER_FORWARD_REWARD_WEIGHT" \
        --log-dir "$SAC_LOG_DIR" \
        --exp-name "$EXP" \
        --baseline-mode "$MODE"
    done
    SEED_SLOT=$((SEED_SLOT + 1))
  done
done

if [[ "$SKIP_PLOTS" == "1" ]]; then
  exit 0
fi

python3 scripts/plot_fedrl_heterogeneous.py \
  --fed-log-dir "$LOG_DIR" \
  --paper-log-dir "$SAC_LOG_DIR" \
  --dqn-log-dir "" \
  --out-dir "$COMPARISON_OUT_DIR" \
  --plot-kind comparison \
  --x-axis "$PLOT_X_AXIS" \
  --metric "$PLOT_METRIC" \
  --variance "$PLOT_VARIANCE" \
  --smooth-window "$PLOT_SMOOTH_WINDOW"

python3 scripts/plot_fedrl_heterogeneous.py \
  --fed-log-dir "$LOG_DIR" \
  --paper-log-dir "$SAC_LOG_DIR" \
  --dqn-log-dir "" \
  --out-dir "$CANDIDATE_OUT_DIR" \
  --plot-kind comparison \
  --x-axis "$PLOT_X_AXIS" \
  --metric candidate \
  --variance "$PLOT_VARIANCE" \
  --smooth-window "$PLOT_SMOOTH_WINDOW"

python3 scripts/plot_fedrl_heterogeneous.py \
  --fed-log-dir "$LOG_DIR" \
  --paper-log-dir "" \
  --dqn-log-dir "" \
  --out-dir "$ABLATION_OUT_DIR" \
  --plot-kind ablation \
  --x-axis "$PLOT_X_AXIS" \
  --metric "$PLOT_METRIC" \
  --variance "$PLOT_VARIANCE" \
  --smooth-window "$PLOT_SMOOTH_WINDOW"

python3 scripts/summarize_fedrl_results.py \
  --fed-log-dir "$LOG_DIR" \
  --paper-log-dir "$SAC_LOG_DIR" \
  --dqn-log-dir "" \
  --out-dir "$SUMMARY_OUT_DIR" \
  --plot-kind comparison \
  --envs $ENVS
